version: "3.1"

services:

  ebaycrawler:
    ports:
      - 4000:4000
    build:
      dockerfile: Dockerfile


  chrome-browser:
    image: tobesocial/playwright-browser
    ports:
      - 3000:3000
    environment:
      - FLAG__debug_print=false
      - FLAG_chromium__allow_sandbox_debugging=false
    hostname: chrome-browser


  mongo:
    image: mongo:4.4.6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-volume:/data/db
    command: mongod --quiet --logpath /dev/null 

volumes:
  mongo-volume:
